# Generated by Django 5.2.5 on 2025-08-25 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_image_productimage_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='image_url',
            new_name='images',
        ),
    ]
