# Generated by Django 5.2.5 on 2025-08-25 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_image_url_productimage_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='images',
            new_name='image',
        ),
    ]
